env:
   - TERM=dumb
language: java
dist: trusty
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.4
  allow_failures:
    - jdk: openjdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: ./gradlew clean
script: ./gradlew build shadowJar proguard
branches:
  only:
    - master
    - stable
